sonar.projectKey=wanderberriel_devops-audit-pipeline
sonar.organization=wanderberriel
sonar.projectName=devops-audit-pipeline

# Encoding
sonar.sourceEncoding=UTF-8

# Exclusões padrão
sonar.exclusions=**/*.yml,**/*.yaml,**/docs/**,**/k8s/**,**/node_modules/**,**/dist/**,**/bin/**,**/obj/**
